---@enum eFRONTEND_INPUT
eFRONTEND_INPUT =
{
    FRONTEND_INPUT_UP = 0,
    FRONTEND_INPUT_DOWN = 1,
    FRONTEND_INPUT_LEFT = 2,
    FRONTEND_INPUT_RIGHT = 3,
    FRONTEND_INPUT_RDOWN = 4,
    FRONTEND_INPUT_RLEFT = 5,
    FRONTEND_INPUT_RRIGHT = 6,
    FRONTEND_INPUT_RUP = 7,
    FRONTEND_INPUT_ACCEPT = 8,
    FRONTEND_INPUT_X = 9,
    FRONTEND_INPUT_Y = 10,
    FRONTEND_INPUT_BACK = 11,
    FRONTEND_INPUT_START = 12,
    FRONTEND_INPUT_SPECIAL_UP = 13,
    FRONTEND_INPUT_SPECIAL_DOWN = 14,
    FRONTEND_INPUT_RSTICK_LEFT = 15,
    FRONTEND_INPUT_RSTICK_RIGHT = 16,
    FRONTEND_INPUT_LT = 17,
    FRONTEND_INPUT_RT = 18,
    FRONTEND_INPUT_LB = 19,
    FRONTEND_INPUT_RB = 20,
    FRONTEND_INPUT_LT_SPECIAL = 21,
    FRONTEND_INPUT_RT_SPECIAL = 22,
    FRONTEND_INPUT_SELECT = 23,
    FRONTEND_INPUT_R3 = 24,
    -- Used for pointing devices (mouse button, touch pad etc).
    FRONTEND_INPUT_CURSOR_ACCEPT = 25,
    FRONTEND_INPUT_CURSOR_BACK = 26,
    FRONTEND_INPUT_L3 = 27,
    FRONTEND_INPUT_MAX = 28
}

---@enum CHECK_INPUT_OVERRIDE_FLAG
CHECK_INPUT_OVERRIDE_FLAG =
{
    CHECK_INPUT_OVERRIDE_FLAG_NONE = 0,
    CHECK_INPUT_OVERRIDE_FLAG_WARNING_MESSAGE = (1 << 0),
    CHECK_INPUT_OVERRIDE_FLAG_STORAGE_DEVICE = (1 << 1),
    CHECK_INPUT_OVERRIDE_FLAG_RESTART_SAVED_GAME_STATE = (1 << 2),
    CHECK_INPUT_OVERRIDE_FLAG_IGNORE_ANALOGUE_STICKS = (1 << 3),
    CHECK_INPUT_OVERRIDE_FLAG_IGNORE_D_PAD = (1 << 4)
}

