import {ItemFont} from "./item-font";

export class ScaleformFonts {
    public static CHALET_LONDON_NINETEENSIXTY = new ItemFont("$Font2")
    public static SIGNPAINTER_HOUSESCRIPT = new ItemFont("$Font5")
    /**
     * Weird symbols.. use only numbers!
     */
    public static GTAV_LEADERBOARD = new ItemFont("$GTAVLeaderboard")
    public static CHALET_COMPRIME_COLOGNE_SIXTY = new ItemFont("$Font2_cond")
    public static CHALET_LONDON_NINETEENSIXTY_NUMB = new ItemFont("$FixedWidthNumbers")
    public static PRICEDOWN_GTAV_INT = new ItemFont("$gtaCash")
    public static CHALET_COMPRIME_COLOGNESIXTY_NOT_GAMERNAME = new ItemFont("$Font2_cond_NOT_GAMERNAME")
    public static GTAV_TIMER_FIXED_COND = new ItemFont("$Font2_cond_MPTimer")
    public static ROCKSTAR_TAG = new ItemFont("$RockstarTAG")
    public static HANDSTYLE_HEIST = ItemFont.registerFont("font_lib_editor", "$HandstyleHeist")
    public static REDEMPTION = ItemFont.registerFont("font_lib_editor", "$Redemption")
    public static GTA_SUBTRACT = ItemFont.registerFont("font_lib_editor", "$Subtract")
    public static HELVETICA_55 = ItemFont.registerFont("font_lib_editor", "$Helvetica55")
    public static DIN = ItemFont.registerFont("font_lib_editor", "$Din")
    public static HELVETICA_107 = ItemFont.registerFont("font_lib_editor", "$Helvetica107")
    public static UNIVERS = ItemFont.registerFont("font_lib_editor", "$Univers")
    public static SUBTRACT = ItemFont.registerFont("font_lib_heist4", "$Subtract")
    public static HELVETICANEUE_LT_47_LIGHTCN = ItemFont.registerFont("font_lib_sc", "$SOCIAL_CLUB_COND_REG")
    public static HELVETICANEUE_LT_67_MDCN = ItemFont.registerFont("font_lib_sc", "$SOCIAL_CLUB_COND_BOLD")
    public static GTAV_TAXI_DIGITAL = ItemFont.registerFont("font_lib_taxi", "$Taxi_font")
    public static GTAV_COURIER = ItemFont.registerFont("font_lib_typewriter", "$Courier")
    public static ANNA_SC_ITC_TT = ItemFont.registerFont("font_lib_org", "$AnnaSC")
    public static BAUHAUSITCTT = ItemFont.registerFont("font_lib_org", "$Bauhaus")
    public static BOOKMANMDITCTT = ItemFont.registerFont("font_lib_org", "$Bookman")
    public static ENGRAVERS_OLD_ENGLISH_MT_STD = ItemFont.registerFont("font_lib_org", "$EngraversOldEnglish")
    public static HELVETICA_NEUE_LT_COM_95_BLK = ItemFont.registerFont("font_lib_org", "$HelveticaBLK")
    public static HELVETICA_NEUE_LT_COM_96_BLKIT = ItemFont.registerFont("font_lib_org", "$HelveticaBLKI")
    public static LUBALINGRAPHMDITCTT = ItemFont.registerFont("font_lib_org", "$Lubalin")
    public static MISTRAL_STD = ItemFont.registerFont("font_lib_org", "$Mistral")
    public static STENBERGITC_TT = ItemFont.registerFont("font_lib_org", "$Stenberg")
    public static STENCIL_STD = ItemFont.registerFont("font_lib_org", "$Stencil")
    public static TIMES_NEW_ROMAN = ItemFont.registerFont("font_lib_org", "$Times")
    public static TRADE_GOTHIC_LT_COM_BOLD = ItemFont.registerFont("font_lib_org", "$TradeGothic")
    public static ITC_MACHINE_STD = ItemFont.registerFont("font_lib_org", "$Machine")
    public static HELVETICANEUELT_W1G_55_ROMAN = ItemFont.registerFont("font_lib_org", "$WebFont1_Hbold")
    public static HELVETICANEUELT_W1G_55_ROMAN_2 = ItemFont.registerFont("font_lib_org", "$WebFont2_Hitalic")
    public static TIMES_NEW_ROMAN_CE = ItemFont.registerFont("font_lib_org", "$WebFont3_Times")
    public static COURIER_TWELVE_MT_STD = ItemFont.registerFont("font_lib_org", "$WebFont4_Courier")
    public static BELL_GOTHIC_BLACK = ItemFont.registerFont("font_lib_org", "$WebFont5_BellGothic")
}
